BEGIN;

-- =========================================================
-- 1. EXTENSIONES
-- =========================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;


-- =========================================================
-- 2. ROLES
-- =========================================================
-- Tabla auxiliar para distinguir USER y ADMIN.

CREATE TABLE public.roles (
    id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    name text NOT NULL UNIQUE,

    CONSTRAINT roles_name_check
        CHECK (name IN ('USER', 'ADMIN'))
);

INSERT INTO public.roles (name)
VALUES
    ('USER'),
    ('ADMIN')
ON CONFLICT (name) DO NOTHING;


-- =========================================================
-- 3. PERFILES
-- =========================================================
-- Un perfil pertenece a un usuario autenticado de Supabase.

CREATE TABLE public.profiles (
    id uuid PRIMARY KEY
        REFERENCES auth.users(id)
        ON DELETE CASCADE,

    role_id smallint NOT NULL
        REFERENCES public.roles(id),

    created_at timestamptz NOT NULL DEFAULT now(),

    updated_at timestamptz NOT NULL DEFAULT now()
);


-- =========================================================
-- 4. CREAR PERFIL AUTOMÁTICAMENTE
-- =========================================================
-- Todo usuario nuevo comienza como USER.

CREATE OR REPLACE FUNCTION public.handle_new_user_profile()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN

    INSERT INTO public.profiles (
        id,
        role_id
    )
    SELECT
        NEW.id,
        r.id
    FROM public.roles r
    WHERE r.name = 'USER'
    ON CONFLICT (id) DO NOTHING;

    RETURN NEW;

END;
$$;


CREATE TRIGGER on_auth_user_created_profile
AFTER INSERT ON auth.users
FOR EACH ROW
EXECUTE FUNCTION public.handle_new_user_profile();


-- =========================================================
-- 5. CREAR PERFILES PARA USUARIOS EXISTENTES
-- =========================================================

INSERT INTO public.profiles (
    id,
    role_id
)
SELECT
    u.id,
    r.id
FROM auth.users u
CROSS JOIN public.roles r
WHERE r.name = 'USER'
ON CONFLICT (id) DO NOTHING;


-- =========================================================
-- 6. FUNCIÓN PARA COMPROBAR ADMIN
-- =========================================================

CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT EXISTS (
        SELECT 1
        FROM public.profiles p
        INNER JOIN public.roles r
            ON r.id = p.role_id
        WHERE p.id = auth.uid()
          AND r.name = 'ADMIN'
    );
$$;


-- =========================================================
-- 7. TABLA: inventory_items
-- =========================================================
-- Información maestra de los artículos.

CREATE TABLE public.inventory_items (

    id uuid PRIMARY KEY
        DEFAULT gen_random_uuid(),

    sku text NOT NULL UNIQUE,

    name text NOT NULL,

    description text,

    category text,

    weight numeric,

    length numeric,

    width numeric,

    height numeric,

    price numeric,

    cost numeric,

    supplier text,

    created_at timestamptz NOT NULL
        DEFAULT now(),

    CONSTRAINT inventory_items_weight_check
        CHECK (weight IS NULL OR weight >= 0),

    CONSTRAINT inventory_items_length_check
        CHECK (length IS NULL OR length >= 0),

    CONSTRAINT inventory_items_width_check
        CHECK (width IS NULL OR width >= 0),

    CONSTRAINT inventory_items_height_check
        CHECK (height IS NULL OR height >= 0),

    CONSTRAINT inventory_items_price_check
        CHECK (price IS NULL OR price >= 0),

    CONSTRAINT inventory_items_cost_check
        CHECK (cost IS NULL OR cost >= 0)
);


COMMENT ON TABLE public.inventory_items IS
'Información maestra de los artículos del inventario';


-- =========================================================
-- 8. TABLA: inventory
-- =========================================================
-- Representa el stock actual de cada artículo.
--
-- Relación:
-- inventory_items 1 ─── 1 inventory
--
-- quantity solamente debe cambiar directamente por ADMIN
-- o mediante la función de aprobación de movimientos.

CREATE TABLE public.inventory (

    id uuid PRIMARY KEY
        DEFAULT gen_random_uuid(),

    item_id uuid NOT NULL UNIQUE
        REFERENCES public.inventory_items(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    quantity integer NOT NULL DEFAULT 0,

    location text,

    min_stock integer NOT NULL DEFAULT 0,

    max_stock integer NOT NULL,

    updated_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT inventory_quantity_check
        CHECK (quantity >= 0),

    CONSTRAINT inventory_min_stock_check
        CHECK (min_stock >= 0),

    CONSTRAINT inventory_max_stock_check
        CHECK (max_stock >= min_stock),

    -- Necesaria para garantizar que un movement
    -- use inventory_id + item_id coherentes.
    CONSTRAINT inventory_id_item_id_unique
        UNIQUE (id, item_id)
);


COMMENT ON TABLE public.inventory IS
'Stock actual y configuración de inventario por artículo';


-- =========================================================
-- 9. TABLA: inventory_movements
-- =========================================================
-- Historial de movimientos.
--
-- Relación:
-- inventory 1 ─── N inventory_movements

CREATE TABLE public.inventory_movements (

    id uuid PRIMARY KEY
        DEFAULT gen_random_uuid(),

    item_id uuid NOT NULL,

    inventory_id uuid NOT NULL,

    movement_type text NOT NULL,

    quantity integer NOT NULL,

    reason text,

    status text NOT NULL DEFAULT 'PENDIENTE',

    created_at timestamptz NOT NULL DEFAULT now(),

    approved_at timestamptz,

    rejected_at timestamptz,

    notes text,

    CONSTRAINT inventory_movements_quantity_check
        CHECK (quantity > 0),

    CONSTRAINT inventory_movements_type_check
        CHECK (
            movement_type IN (
                'ENTRADA',
                'SALIDA',
                'AJUSTE'
            )
        ),

    CONSTRAINT inventory_movements_status_check
        CHECK (
            status IN (
                'PENDIENTE',
                'APROBADO',
                'RECHAZADO'
            )
        ),

    CONSTRAINT inventory_movements_item_fk
        FOREIGN KEY (item_id)
        REFERENCES public.inventory_items(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT inventory_movements_inventory_fk
        FOREIGN KEY (inventory_id)
        REFERENCES public.inventory(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    -- Garantiza que inventory_id pertenezca
    -- al mismo item_id indicado en el movimiento.
    CONSTRAINT inventory_movements_inventory_item_fk
        FOREIGN KEY (inventory_id, item_id)
        REFERENCES public.inventory(id, item_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);


COMMENT ON TABLE public.inventory_movements IS
'Historial de entradas, salidas y ajustes del inventario';


-- =========================================================
-- 10. FUNCIÓN PARA updated_at
-- =========================================================

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN

    NEW.updated_at = now();

    RETURN NEW;

END;
$$;


-- =========================================================
-- 11. TRIGGERS updated_at
-- =========================================================

CREATE TRIGGER set_inventory_updated_at
BEFORE UPDATE ON public.inventory
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();


CREATE TRIGGER set_profiles_updated_at
BEFORE UPDATE ON public.profiles
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();


-- =========================================================
-- 12. ÍNDICES
-- =========================================================

CREATE INDEX idx_profiles_role_id
    ON public.profiles(role_id);


CREATE INDEX idx_inventory_movements_item_id
    ON public.inventory_movements(item_id);


CREATE INDEX idx_inventory_movements_inventory_id
    ON public.inventory_movements(inventory_id);


CREATE INDEX idx_inventory_movements_status
    ON public.inventory_movements(status);


CREATE INDEX idx_inventory_movements_created_at
    ON public.inventory_movements(created_at);


CREATE INDEX idx_inventory_items_category
    ON public.inventory_items(category);


CREATE INDEX idx_inventory_items_supplier
    ON public.inventory_items(supplier);


-- =========================================================
-- 13. FUNCIÓN: APROBAR MOVIMIENTO
-- =========================================================
-- Solamente ADMIN puede aprobar.
--
-- ENTRADA:
--     quantity aumenta.
--
-- SALIDA:
--     quantity disminuye.
--
-- AJUSTE:
--     quantity aumenta según la cantidad indicada.
--
-- El movimiento debe estar PENDIENTE.
--
-- El stock nunca puede quedar negativo.

CREATE OR REPLACE FUNCTION public.approve_inventory_movement(
    p_movement_id uuid
)
RETURNS public.inventory_movements
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$

DECLARE
    v_movement public.inventory_movements;
    v_inventory public.inventory;
    v_new_quantity integer;

BEGIN

    -- -----------------------------------------------------
    -- VALIDAR ADMIN
    -- -----------------------------------------------------

    IF NOT public.is_admin() THEN
        RAISE EXCEPTION
            'Solo un ADMIN puede aprobar movimientos';
    END IF;


    -- -----------------------------------------------------
    -- BLOQUEAR EL MOVIMIENTO
    -- -----------------------------------------------------

    SELECT *
    INTO v_movement
    FROM public.inventory_movements
    WHERE id = p_movement_id
    FOR UPDATE;


    IF NOT FOUND THEN
        RAISE EXCEPTION
            'Movimiento no encontrado';
    END IF;


    -- -----------------------------------------------------
    -- SOLO SE PUEDEN APROBAR MOVIMIENTOS PENDIENTES
    -- -----------------------------------------------------

    IF v_movement.status <> 'PENDIENTE' THEN
        RAISE EXCEPTION
            'El movimiento ya fue procesado';
    END IF;


    -- -----------------------------------------------------
    -- BLOQUEAR INVENTARIO
    -- -----------------------------------------------------

    SELECT *
    INTO v_inventory
    FROM public.inventory
    WHERE id = v_movement.inventory_id
      AND item_id = v_movement.item_id
    FOR UPDATE;


    IF NOT FOUND THEN
        RAISE EXCEPTION
            'El registro de inventario no existe';
    END IF;


    -- -----------------------------------------------------
    -- CALCULAR NUEVO STOCK
    -- -----------------------------------------------------

    IF v_movement.movement_type = 'ENTRADA' THEN

        v_new_quantity :=
            v_inventory.quantity + v_movement.quantity;

    ELSIF v_movement.movement_type = 'SALIDA' THEN

        v_new_quantity :=
            v_inventory.quantity - v_movement.quantity;

    ELSIF v_movement.movement_type = 'AJUSTE' THEN

        v_new_quantity :=
            v_inventory.quantity + v_movement.quantity;

    END IF;


    -- -----------------------------------------------------
    -- EVITAR STOCK NEGATIVO
    -- -----------------------------------------------------

    IF v_new_quantity < 0 THEN
        RAISE EXCEPTION
            'Stock insuficiente para aprobar la salida';
    END IF;


    -- -----------------------------------------------------
    -- ACTUALIZAR STOCK
    -- -----------------------------------------------------

    UPDATE public.inventory
    SET
        quantity = v_new_quantity,
        updated_at = now()
    WHERE id = v_inventory.id;


    -- -----------------------------------------------------
    -- MARCAR MOVIMIENTO COMO APROBADO
    -- -----------------------------------------------------

    UPDATE public.inventory_movements
    SET
        status = 'APROBADO',
        approved_at = now()
    WHERE id = p_movement_id;


    -- -----------------------------------------------------
    -- DEVOLVER MOVIMIENTO ACTUALIZADO
    -- -----------------------------------------------------

    SELECT *
    INTO v_movement
    FROM public.inventory_movements
    WHERE id = p_movement_id;


    RETURN v_movement;

END;
$$;


-- =========================================================
-- 14. FUNCIÓN: RECHAZAR MOVIMIENTO
-- =========================================================
-- Solamente ADMIN puede rechazar.
--
-- Rechazar NO modifica inventory.quantity.

CREATE OR REPLACE FUNCTION public.reject_inventory_movement(
    p_movement_id uuid,
    p_reason text DEFAULT NULL
)
RETURNS public.inventory_movements
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$

DECLARE
    v_movement public.inventory_movements;

BEGIN

    -- -----------------------------------------------------
    -- VALIDAR ADMIN
    -- -----------------------------------------------------

    IF NOT public.is_admin() THEN
        RAISE EXCEPTION
            'Solo un ADMIN puede rechazar movimientos';
    END IF;


    -- -----------------------------------------------------
    -- RECHAZAR SOLO SI ESTÁ PENDIENTE
    -- -----------------------------------------------------

    UPDATE public.inventory_movements
    SET
        status = 'RECHAZADO',
        rejected_at = now(),
        notes = COALESCE(p_reason, notes)
    WHERE id = p_movement_id
      AND status = 'PENDIENTE'
    RETURNING *
    INTO v_movement;


    IF NOT FOUND THEN
        RAISE EXCEPTION
            'El movimiento no existe o ya fue procesado';
    END IF;


    RETURN v_movement;

END;
$$;


COMMIT;